In [1]:
import numpy as np
import pandas as pd 

In [2]:
df=pd.read_csv("E:\movie imdb\ADANIPORTS.csv")
df.head(1)

<>:1: SyntaxWarning: invalid escape sequence '\m'
<>:1: SyntaxWarning: invalid escape sequence '\m'
C:\Users\ankit\AppData\Local\Temp\ipykernel_22612\2616891743.py:1: SyntaxWarning: invalid escape sequence '\m'
  df=pd.read_csv("E:\movie imdb\ADANIPORTS.csv")


Date      Symbol Series  PrevClose   Open    High    Low   Last  \
0  27-11-2007  MUNDRAPORT     EQ      440.0  770.0  1050.0  770.0  959.0   

   Close    VWAP    Volume      Turnover  Trades  Deliverable Volume  \
0  962.9  984.72  27294366  2.687720e+15     NaN             9859619   

   %Deliverble  
0       0.3612

In [3]:
x=df.iloc[:,3:8].values
y=df.iloc[:,8].values

In [4]:
x

array([[ 440.  ,  770.  , 1050.  ,  770.  ,  959.  ],
       [ 962.9 ,  984.  ,  990.  ,  874.  ,  885.  ],
       [ 893.9 ,  909.  ,  914.75,  841.  ,  887.  ],
       ...,
       [ 749.15,  755.  ,  760.  ,  741.1 ,  743.4 ],
       [ 746.25,  753.2 ,  765.85,  743.4 ,  746.4 ],
       [ 746.75,  739.  ,  759.45,  724.5 ,  726.4 ]])

In [5]:
y

array([962.9 , 893.9 , 884.2 , ..., 746.25, 746.75, 730.05])

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [8]:
from sklearn.svm import SVR

In [9]:
model = SVR(kernel='poly',degree=2,C=2)

In [10]:
model.fit(x_train, y_train)

SVR(C=2, degree=2, kernel='poly')

In [11]:
y_pred = model.predict(x_test)

In [12]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [13]:
MAE = mean_absolute_error(y_test,y_pred)
MSE = mean_squared_error(y_test,y_pred)
RMSE = np.sqrt(MSE)

In [14]:
MAE

np.float64(43.19498457634986)

In [15]:
MSE

np.float64(6125.7435755133665)

In [16]:
RMSE

np.float64(78.26712959802069)

In [17]:
model.predict([[440,770,1050,770,959]])

array([906.24921285])